export const SET_STUDENT_LIST = "SET_STUDENT_LIST";
export const SET_SELECTED_STUDENT = "SET_SELECTED_STUDENT";
export const RESET_SELECTED_STUDENT = "RESET_SELECTED_STUDENT";
export const SET_LOADING = "SET_LOADING";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
